#These are the ending credits
import time
import sys
import shutil
import winsound

winsound.PlaySound('credits Music.wav', winsound.SND_FILENAME | winsound.SND_ASYNC)

print("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
time.sleep(10)
columns = shutil.get_terminal_size().columns
print("Shadow of the Amarok".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Credits:".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Game Director".center(columns))
time.sleep(0.4)
print("Fritz Hesse".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print('Writer'.center(columns))
time.sleep(0.4)
print("Fritz Hesse".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print('"Artist"'.center(columns))
time.sleep(0.4)
print("Fritz Hesse".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Programmer".center(columns))
time.sleep(0.4)
print("Fritz Hesse".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Programming Advisor".center(columns))
time.sleep(0.4)
print("Jordan Gaines".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Writing Advisor".center(columns))
time.sleep(0.4)
print("Getty Hesse".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Music".center(columns))
time.sleep(0.4)
print("James Shao".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Editors".center(columns))
time.sleep(0.4)
print("Fritz Hesse".center(columns))
time.sleep(0.4)
print("Jordan Gaines".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Special Thanks".center(columns))
time.sleep(0.4)
print("Greg Hesse".center(columns))
time.sleep(0.4)
print("Tish Hesse".center(columns))
time.sleep(0.4)
print("Getty Hesse".center(columns))
time.sleep(0.4)
print("Hans Hesse".center(columns))
time.sleep(0.4)
print("Jordan Gaines".center(columns))
time.sleep(0.4)
print("Mason Westkaemper".center(columns))
time.sleep(0.4)
print("Antonio Quinones".center(columns))
time.sleep(0.4)
print("Canyon Kyle".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Thanks for playing my game!".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Keep an eye out for our next game, Manmade Gods!".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
