import time
import sys
import shutil
import winsound
#this is for the email intro

print("Thank You for Choosing Ether-Mail.")
print("Please Insert Username and Password:")

for char in "ottofuchs@ethermail.com\n":
    print(char, end="")
    time.sleep(0.1)

for i in range(0, 10):
    print("*", end="")
    time.sleep(0.1)
print("\n", end="")
print("Thank you.")

ib = "..."
sys.stdout.write('Loading Mail')
time.sleep(0.1)
sys.stdout.write('.')
time.sleep(0.5)
sys.stdout.write('.')
time.sleep(1.5)
sys.stdout.write('. ')
sys.stdout.write('Complete!')
sys.stdout.flush()
print(" ")
time.sleep(0.5)
print("Showing newest mail:")
print(" ")
print(" ")
print(" ")
print("-------------------------------------------------")
#this is the email itself; do NOT use any single letter variables after the intro (except for 'c' in the areas where confirmation input is required)
a = "Mr. Fuchs,\n"
b = "We are ready to commence the test. Subject Theta\n"
c = "has been successfully sedated and connected to all\n"
d = "the necessary equipment. Now, I know that there\n"
e = "was an issue with the last test, but we discovered\n"
f = "part of it. It seems that the previous vessel’s\n"
g = "geomagnets were not able to produce enough dark\n"
h = "energy to counteract the g-forces. This time, we are\n"
i = "using a retrofitted destroyer so we should be in the\n"
j = "clear. Just give us the go ahead and we will start\n"
k = "the test.\n"
l = "Dr. Jared Stevenson, PhD, EDR Team Leader\n"
for char in a:
    print("%s" % char, end="")
    time.sleep(0.01)
for char in b:
    print("%s" % char, end="")
    time.sleep(0.01)
for char in c:
    print("%s" % char, end="")
    time.sleep(0.01)
for char in d:
    print("%s" % char, end="")
    time.sleep(0.01)
for char in e:
    print("%s" % char, end="")
    time.sleep(0.01)
for char in f:
    print("%s" % char, end="")
    time.sleep(0.01)
for char in g:
    print("%s" % char, end="")
    time.sleep(0.01)
for char in h:
    print("%s" % char, end="")
    time.sleep(0.01)
for char in i:
    print("%s" % char, end="")
    time.sleep(0.01)
for char in j:
    print("%s" % char, end="")
    time.sleep(0.01)
for char in k:
    print("%s" % char, end="")
    time.sleep(0.01)
print(" ")
for char in l:
    print("%s" % char, end="")
    time.sleep(0.01)
print("-------------------------------------------------")
print(" ")
print(" ")
print(" ")
print("-------------------------------------------------")
#if player needs to confirm to continue, ENTER. NOTHING ELSE
q = input("press ENTER to continue: ")
print(" ")
print(" ")
print(" ")
print("-------------------------------------------------------------------------------------------------------------------")
#don't mess with this too much; the ascii art was a pain to get to show correctly
print(" ")
print(" ")
print(" ")
print("                                                                                                 .")
time.sleep(0.01)
print("                                                                                                `h")
time.sleep(0.01)
print("                                                                                                 y      `---::/-.  ")
time.sleep(0.01)
print("                                                                                                 s   ./shhso++++++:.")
time.sleep(0.01)
print("                                                                                                 y.:ydNNmmdys+///++o+-")
time.sleep(0.01)
print("                                                                                                .dhmNNNNNmmddyssoyyyss.")
time.sleep(0.01)
print("                                                                                               -yNNNNNNNNNNmddhhhhhhhy/")
time.sleep(0.01)
print("                                                                                    `..----..:smNNmmddddmmmddddhhddhhh+ ")
time.sleep(0.01)
print("                                                                               `-:PERSPICACIOUS ENTERTAINMENT PRESENTS+")
time.sleep(2)
print("                                                                              -ydddmNMMMMmNMMMMMMMMMMMMMNddhdhdhdhhhhhdh.")
time.sleep(0.01)
print("                                                                             -dmdddmNMMMMdNNMNNNNNNmmdddhhhdddddysshhhho`")
time.sleep(0.01)
print("                                                                   ```.....`:mNNNddmNMMMMNMNNNNNNNNNNNmmhhdmddyssooshmh:")
time.sleep(0.01)
print("                                                               `:sysooyddysohNNNmdmmNMMNNNNNNNNNNNNNNNNNNmmmmhyso++osso:")
time.sleep(0.01)
print("                                                             .odNNNdsoosdmhsshNNhdmdhhhmMMNMMNNNNNNNMMMMMMMMMNdyso+++/ ")
time.sleep(0.01)
print("                                                            `hNNNNNNmhsosdmhsymMmhddhooymMMMMMNMNmmNNNNNNMMMMMNmhysoo+")
time.sleep(0.01)
print("                                                            +NNNNNNNNNNhsoyyyhmMMNdddyysymNNMMMMMMNmNNNNNNNNNNNNNmdh+")
time.sleep(0.01)
print("                                                           .dNNNNNNNNNNNmhssshmMMMNmdddyssdNMMMMMMMMMMMmmNNNNNNNNNd:")
time.sleep(0.01)
print("                                                           sNNNNNNNNNNNNNNmhhdmMMMMNmddhyyhmNMMmdNMMMMNddNMMMMmysso/.")
time.sleep(0.01)
print("                                                           hNNNNNNNNNNNNNNNmmmNMMMMMMmdysossyhyoooyhmdsoshNNmdyyyoooo/.")
time.sleep(0.01)
print("                                                           hNNNNNNNNNNNNNNNNmmNMMMMMMNmyoooooosdooooooooooosoosoydhsooo/` ")
time.sleep(0.01)
print("                                                           sNNNNNNMNNNNNNNNNmmNMMMMMMNNNyoooooodhooooooooooooooyshNmssoys.  ")
time.sleep(0.01)
print("                                                           oNNNNNNNNNNNNNNNmmmmMMMMMMMNNNyooooooysooooooooooooosmsNNysshhs ")
time.sleep(0.01)
print("                                                           sNNNNNMMMMNNMMMNmmmmNNMMMMMNNNdsossoooyoooossooooooooyshNhysydy ")
time.sleep(0.01)
print("                                                          `dNNNNNMMMMMMMMMMNmddmNMMMMMMMNNysssssoysssyyssssoooossysmmyssds")
time.sleep(0.01)
print("                                                          omdmNNMMMMMMMMMMMMNddmNMMMMMMMMMNdyssysssyyysssssssossshsyNdsshy ")
time.sleep(0.01)
print("                                                         `mMMMMMMMMMMMMMMMMMNmmmNMMMMMMMMMMNdsssssossssysyyssosysssyNNhssds ")
time.sleep(0.01)
print("                                                         omNNMMMMMMMMMMMMMMMNmmNNMMMMMMMMMMNNhysossoosossssyooysoosmNNNyssy+")
time.sleep(0.01)
print("                                                        `mmmmmNMMMMMMMMMMMMMMmmmNMMMMMMMMMNNmmmmdhysossssssyosyooodmNNNNysss.")
time.sleep(0.01)
print("                                                       `dmNNNMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMNNmmmmmmmmmdhhhhhyhhhdmmmNNNNNmmmh`")
time.sleep(0.01)
print("                                                       +mmMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmmmmmmmmmdddddhhhhmmmmNNNNNmmmm-    ")
time.sleep(0.01)
print("                                                      `dmmMNMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMNNNNmmmmmmmmmmmdddddhdmmmmNNNNNddhhy.")
time.sleep(0.01)
print("                                                      /mmmNMMMMMMMMMMMMM:-MMMMMMMMMMMMMMMMMMNNNmmmmmmmmmmmddddhmmmmNMNNNNmssss+ ")
time.sleep(0.01)
print("                                                      dmmmNMMMMMMMMMMMMs  mMMMMMMMMMMMMMMMMMMNNNNmmmmmmmmmmddddmmmmNMNNNNNmysss:")
time.sleep(0.01)
print("                                                     /mmmNMMMMMMMMMMNmd`  dMMMMMMMMMMMMMMMMMMMMNNNmmmmmmmmmddddmmmmNNNNNMMMNhsso:")
time.sleep(0.01)
print("                                                     dmmmMMMMMMMMMMNdy.   dMMMMMMMMMMMMMMMMMMMMMMNmhhhhhhhhdddhhhhyNNNNMMMNNNmyss/`")
time.sleep(0.01)
print("                                                    :mmmNMMMNMNMMMMh+`    yMMMMMMMMMMMMMMNNMMMMMMMNmhhyssssyyysssssmNNNNMMMNNNdyss+.")
time.sleep(0.01)
print("                                                    hmmNMMMNMNNMMN/`      +MMMMMMMMMMNNNNNNmmmNNNMMNmhyysssdmmmyooshmNNNNNMMMMMdysso/`")
time.sleep(0.01)
print("                                                   :mmNMMMMMMNMMm-        -MMMMMMMMMMMNNMMMMNNNmmNNMMNdhyssyNMNhsoshmmmmNMMMMMMNmysooo/:--` ")
time.sleep(0.01)
print("                                                  `ymmMMMMMMNNMm.          mMMMMMMMMMMNNMMMMMMNNmmmNMMMNdyssymNmyssdMNmdmNMMMMMMNhyyyyssssoo:")
time.sleep(0.01)
print("                                                .+mmmNMMMMMMMMm.           +NMmddNMMMMMMNMMMMMMMNNmMMNMMNmhsssyyssshMMNhydNNMMMMNdssyhhddddsy`   `")
time.sleep(0.01)
print("                                               ymMMMMMMMMMMMMM-             ...``-yNMMMNNMMMMMMMNNNNMMMMMmhysossssssmMMmhdNNNMNmhshmNMMMMMNdhssyyy+-")
time.sleep(0.01)
print("                                               mMMMMMMMMMMMMMMo++/`                oMMMMMMMMMMMMNNNNMMMMMhhyyyysyyyssyNmhdNNNNdysdMMNNmdhhhhhhhhyyyyo-")
time.sleep(0.01)
print("                                               -hNMMMMMMMMMMMMMMMMh`               :NMMMMMMMMMMMNmNNNMMMMNNNNNmdhmmmmmNmddNNNNysdMMNmhyyyyymNNNmysssoo/-`")
time.sleep(0.01)
print("                                               .+mMMMMMMMMMMMMMMMMm.               +MMMMMMMNMMMMNmNNNMMMMMMNNNNmmNNNNNMdddmdmmyyMMNNNNmmmmhyhNNhsssooooooo-")
time.sleep(0.01)
print("                                          ./shdmNNNNNMMMMMMNmNNNm+               `yMMMNMMMNMMMMNmNNNMMMMMNNNNNNNNNNNMNdddo`.-:sNMMMMMMMMMNmyhNNdysssoososh-")
time.sleep(0.01)
print("                                          `dmmmmdddddmmmmNMMo----.              `-hNMM A GAME BY FRITZ HESSE MMMMNNNNNNNNd-    +mMMMMMMMMMMMmhhdNmyyssooossy:")
time.sleep(3)
print("                                          /NmmmmddddddmmmmNM/               .:/symNNMMMMMMMMMMMMmmmmNMMMMMNNNNNNNNNNMMddd+     +NMMMMNNNMMMMMNdhdNmhyssssyssy+")
time.sleep(0.01)
print("                                          oNNNNmmmNMNmmNNmNM/             .ymmNNNNNMMMMMMMMMMMMMddddNMMMMMNNNNNNNNNNMNNmh`     .dMMMMMNNNNNNMMNmddmdhyyysssssyo")
time.sleep(0.01)
print("                                          yMNNNNmmNNNmmNMmNM/           .ydNNNNNNmmmmmmNNMMMMMMmmmmNMMMMMNNNNNNNNNNMMMNd:       -mMMMMMNNNNNNMMNNmdddhhhyyysssy+")
time.sleep(0.01)
print("                                         -NMMNNNmmNNNmmNMmNM/          -dNNMMMMMNmdddhhhhhmNMMMNNMMMMMMMMNNNNNNNNNMMmdhy-        :mMMMMMNNNNMMMMNNNmdddhhhyysssso`")
time.sleep(0.01)
print("                                        `dMMNNNNmmNNNmmNMmNM/         :mMMMMMMMMMMMMNmmmddhhhdNMMMMMMMMMMNNNNNNNNNMMmysss.        /NMMMMMMMNNNMMMNNNNmddhhyysoosss`")
time.sleep(0.01)
print("                                        yNNNNNNNmmNNNmmNMmNM/        :mMMMMMMMMMMMMMMNNmNNdhhyydNMMMMMMMNNNNNNNNNMMMMmssso`        yMMMMMMMMMMMMMMNNNmddhhyysssssss.")
time.sleep(0.01)
print("                                       /NNNNNNNNNmmNNmmNMmNM+        :NMMMMMMMMMMMMMMMNNNMNmdhyymMNNMMNNNNNNNNNNMMMMMMdsss+`       .mMMMMMMMMMMMMMMNNmddhhyssssssssy.")
time.sleep(0.01)
print("                                      `dNNNNNNNNNmmmmmmNMmNMh         hMMMMMMMMMMMMMMMNNNMMNNNmmNMNNMMNNNNNNNNNNMMMMMMMhssso`       :mMMMMMMMMMMMMMMMNmhhyyyyssssssss.")
time.sleep(0.01)
print("                                      +NNNMNNNNNNmmmmmmNMmNMN`        `mMMMMMMMMMMMMMMMMMMMMMNNNMMNNMMNNNNNNNNNMMMMMMMMMyssso`       :mMMMMMMMMMMMMMMMNdyyyyyyssssssso.")
time.sleep(0.01)
print("                                      dNNMMMMMMNNNmmmmmNMmNMM-         +MMMMMMMMMMMMMMMMMMMMMNNNNNNMMNNNNNNNNNNMMMNNMMMMNyssyo`       .mMMMMMMMMMMMMMNNNdyyyyssssssssss.")
time.sleep(0.01)
print("                                     .NNMMMMMMMNNmmmmmmmNNMMM/         dMMMMMMMMMMMMMMNMMMMNNNNNNMMMMNNNNNNNNNMMMMMMMMMMMyyyyyo        .dMMMMMMMMMMMMMNNNdyysysyyhdmmmh:")
time.sleep(0.01)
print("                                     /NNMMMMMMMNNNmmmmNNMMMMM/         dMM WITH PROGRAMMING HELP FROM JORDAN GAINES NmmmmmMMMMM         .dMMMMMMMMMMMMMNNNmhhmNNMMMMNm/ ")
time.sleep(3)
print("                                     +NNMMMMMMMMNNmmmmNNMMMMM+         `yMMMMMMMMMMMMMMMMNNmhhhhhdMMMNNNmmmmNMMMMMMMMMMNmmmmNy.          `/oshNMMMMMMMMMMNMMMMMMMMMd/.")
time.sleep(0.01)
print("                                     +NNMMMMMMMMNNmmmmNNMMMMM+           :::NMMMMMNNMMMMMNNNdhhhhhdNMMNmmmmNMMMMMMMMMMNdddddm/                .oNMMMMMMMMMMMMMMMMMMy")
time.sleep(0.01)
print("                                     .mNMMMMMMMMNNmmmmNNMMMMM+              /MMMMMMMMMMMNNNNmdhhhhhhmMMNNNNMMMMMMMMMNmhyyyyyhh+.                -dNMMMMMMMMMMMMMMMMMy.")
time.sleep(0.01)
print("                                      -mMMMMMMMMNNmmmmNNMMMMM+               sMMMMMMMMMNNNNNmdhhhhhhymMMMMMMMMMNNNNmmddhhhhyyyhd                 `::.`.odMMMMMMMMMMMMN+")
time.sleep(0.01)
print("                                       -MMMMMMMMNNmmmmNNMMMMM:                hMMMMMMMNNNNNNmddhhhhhhhmNMMMMMNNNNNNmmmmhhhhhyyyh:                        +MMMMMMMMMMMMm")
time.sleep(0.01)
print("                                        mMMMMMMMNNmdmmNNMMMMM.                `yMMMMMNNNNNNNmddhhhhhhhhdmMMMMNNNNNNmmmmdhyyyyyyyy                        `mMMMMMMMMMMMM/")
time.sleep(0.01)
print("                                        dMMMMMMNNNNNNNNNMMMMN                  `mMMMNNNNNNNNNmddddhhhhhdmNMMMNNNNNNNmmmmdhyyyyyyh:                        :hMMMMMMMMMMMNo`  ")
time.sleep(0.01)
print("                                       `NMNNNMNNMNNNNNNNNNNNm                   /NMMNNNNNNNNNmmddddhhhhddmmNMMNNNNNNNmdmdhhyyyhyyy                          /NMMMMMMMMMMMm:.")
time.sleep(0.01)
print("                                       oNNNNNNNNNNNNNNNNNNNmm`                   hNMMNNNNNNNNNmmddddhhhddmmmMMMNNNNNNNmmdhhyyhhhhh-                          -mMMMMMMMMMMMNN/")
time.sleep(0.01)
print("                                       NNNmNNNNNNNNNNNMNNNNNm:                   `hMMMNNNNNNNNNmmddddhhhdmmNNMMNNNNNNNNNmdhhyyhhhhy                           `dMMMMMMMMMMMMm")
time.sleep(0.01)
print("                                       NNNNNNNMMMMMMMMMMMMMNN/                    `yMMMNNNNNNNNNmmdddddhhdmmNMMMNNNNNNNNNdhhyyhhhhh:                           .NMMMMMMMMMMMMy`")
time.sleep(0.01)
print("                                       sNNNNMMMMMMMMMMMMMMMMo                      `hMMNNNNNNNNNNmmdddddhddmNMMMMNNNNNNNNmhhhhhhhhhs                            /MMMMMMMMMMMMMh`")
time.sleep(0.01)
print("                                       `yNNMMMMMMMMNNNMMMMNo                        .yMMNNNNNNNNNNmmddddhhhdNMMMMNNNNNNNNNdhhhhhhhhh-                            dMMMMMMMMMMMMMd`")
time.sleep(0.01)
print("                                        `yNMMMMMMMMNNNNds/.                          `hMMNNNNNNNNNNmmmmdhhhhmMMMMMNNNNNNNNNhhhhhhhhhy                            `:sMMMMMMMMMMMMy ")
time.sleep(0.01)
print("                                          -/+ossssyso/.`                              yMMMNNNNNNNNMMMNNmdhhhdNMMMMNMMMMNNNNdhhhhhhhhh-                              /mMMMMMMMMN/` ")
time.sleep(0.01)
print("                                                                                     `NMMMMNNNNNMMMMMNNmdhhhdmMMMNMMMMMMNNNNdhhhhhhhd+                               /NMMMNNm+:")
time.sleep(0.01)
print("                                                                                     /MMMMMMMMNNNNMMMNNmdhhhdmMMMMMMMMMMNNNNdhhhhhhhdd`                               `++/:..`")
time.sleep(0.01)
print("                                                                                     hMMMMMMNNNNNNmNMMNNdhhhhdmNMMMMMMMMMNNNNddhhhhmN-")
time.sleep(0.01)
print("                                                                                    `MMMMMMMMNNNNNmNMMMNmhhhhhmNNMMMMMMMMMNNNmmddddmNh.")
time.sleep(0.01)
print("                                                                                    +MMMMMMMMMNNNNNmNNNNmdddddmmmmNMMMNNMMNNNNmmddddddyso:")
time.sleep(0.01)
print("                                                                                    hMMMMMMMMMMMNmmmmNNNNNNNNNNNNNNNMMmmMMMNNmdddddmmNmNNm:")
time.sleep(0.01)
print("                                                                                   `NMMMMMMMMMMMNmNMMMMMMMMMMMMMMMMMMMmmNMMNNmdmNMMMMMMMMMo")
time.sleep(0.01)
print("                                                                                   /MMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMNmmNMMMMNNMMMMMMMMMMMo")
time.sleep(0.01)
print("                                                                                   hMMMMMMMMMNNMNMMMMMMMMMMMMMMMMMMMMmmmNMMMMMMMMMMMMMMMMM/")
time.sleep(0.01)
print("                                                                                  `NMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMmmmMMMMMMMMMMMMMMMMMMN.")
time.sleep(0.01)
print("                                                                                  /MMMMMMMMMNNNNMMMMMMMMMMMMMMMNmMMNmmmmNMMMMMMMMMMMMMMMMy")
time.sleep(0.01)
print("                                                                                  +MMMMMMMMNNNNNMMMMMMMMMMMMMMN:dMNmmNNNMMMMMMMMMMMMMMMMm.")
time.sleep(0.01)
print("                                                                                  +MMMMMMMMNNNNMMMMMMMMMMMMMMM+oMMNNNNMMMMMMMMMMMMMMMMMd-")
time.sleep(0.01)
print("                                                                                  `oMMMMMNNNNNMMMMMMMMMMMMMMNd:NMNNNMMMMMMMMMMMMMMMMMMy`")
time.sleep(0.01)
print("                                                                                   -MMMMNNNNNMMMMMMMMMMMMNNysdmMMNMMMMMMMMMMMMMMMMMMNo")
time.sleep(0.01)
print("                                                                                   yMMMMNNNNMMMMMMMMMMMNs-omMMMMMMMMMMMMMMMMMNNmdddh/")
time.sleep(0.01)
print("                                                                                   oMMMMNNMMMMMMMMMMMMN: :NMMMMMMMMMMMMMMMMNd+:`")
time.sleep(0.01)
print("                                                                                   oMMMMNNMMMMMMMMMMMNo -mMMMMMMMMMMMMMMMNh:")
time.sleep(0.01)
print("                                                                                 -smMMMMNNMMMMMMMMMMN/ :mNMMMMMMMMMMMMMNy-")
time.sleep(0.01)
print("                                                                                 oMMMMMMMMMMMMMMMMMN- .mMMMMMMMMMMMMMNs.")
time.sleep(0.01)
print("                                                                                 -MMMMMMMMMMMMMMMMN- `hMMMMMMMMMMMMm+`")
time.sleep(0.01)
print("                                                                                 .MMMMMMMMMMMMMMMN:  yMMMMMMMMMMMd/ ")
time.sleep(0.01)
print("                                                                                 .MMMMMMMMMMMMMMN-  oMMMMMMMMMMM+")
time.sleep(0.01)
print("                                                                                 .MMMMMMMMMMMMMN-  .MMMMMMMMMMM+")
time.sleep(0.01)
print("                                                                                 :MMMMMMMMMMMMMo  :mMMMMMMMMMN+")
time.sleep(0.01)
print("                                                                                 oMMMMMMMMMMMMm. oMMMMMMMMMMh-")
time.sleep(0.01)
print("                                                                                /NMMMMMMMMMMMN`-yMMMMMNNNNNm`")
time.sleep(0.01)
print("                                                                               sMMMMMMMMMMMMM++MMMMMMMNNNNN+")
time.sleep(0.01)
print("                                                                             .dMMMMMMMMMMMMMd NMMMMMMMNNNNN:")
time.sleep(0.01)
print("                                                                             hMMMMMMMMMMMMMM- mMMMMMMMNNNNN:")
time.sleep(0.01)
print("                                                                             dMMMMMMMMMMMNNN` -MMMMMMMNNNNN/")
time.sleep(0.01)
print("                                                                             yMMMMMMMMMMMMNN.  +MMMMMMMMMNNs")
time.sleep(0.01)
print("                                                                             `dMMMMMMMMMMMNN/   mMMMMMMMMMMh")
time.sleep(0.01)
print("                                                                              `dMMMMMMMMMMMNm+` mMMMMMMMMMMMy`")
time.sleep(0.01)
print("                                                                               `mMMMMMMMMMMNNNy yMMMMMMMMMMMMy")
time.sleep(0.01)
print("                                                                                /MMMMMMMMMMMMNNs-mMMMMMMMMMMMM-")
time.sleep(0.01)
print("                                                                                 hMMMMMMMMMMMMMMm+omMMMMMMMMMM+")
time.sleep(0.01)
print("                                                                                 .NMMMMMMMMMMMMMMN.`smMMMMMMMM+")
time.sleep(0.01)
print("                                                                                  +MMMMMMMMMMMMMMMm. `:oooooo+`")
time.sleep(0.01)
print("                                                                                   dMMMMMMMMMMMMMMMs")
time.sleep(0.01)
print("                                                                                   /MMMMMMMMMMMMMMMs")
time.sleep(0.01)
print("                                                                                   `NMMMMMMMMMMMMMMs")
time.sleep(0.01)
print("                                                                                    :dNMMMMMMMMMMMN-")
time.sleep(0.01)
print("                                                                                      -+hmmmmmmddy-")
time.sleep(0.01)
print("                                                                                         ......`")
time.sleep(.5)
print(" ")
print(" ")
print(" ")
print("   _____ _               _                        __   _   _                                               _    ")
time.sleep(0.01)
print("  / ____| |             | |                      / _| | | | |              /\                             | |   ")
time.sleep(0.01)
print(" | (___ | |__   __ _  __| | _____      __   ___ | |_  | |_| |__   ___     /  \   _ __ ___   __ _ _ __ ___ | | __")
time.sleep(0.01)
print("  \___ \| '_ \ / _` |/ _` |/ _ \ \ /\ / /  / _ \|  _| | __| '_ \ / _ \   / /\ \ | '_ ` _ \ / _` | '__/ _ \| |/ /")
time.sleep(0.01)
print("  ____) | | | | (_| | (_| | (_) \ V  V /  | (_) | |   | |_| | | |  __/  / ____ \| | | | | | (_| | | | (_) |   < ")
time.sleep(0.01)
print(" |_____/|_| |_|\__,_|\__,_|\___/ \_/\_/    \___/|_|    \__|_| |_|\___| /_/    \_\_| |_| |_|\__,_|_|  \___/|_|\_\ ")
time.sleep(0.01)
print("-----------------------------------------------------------------------------------------------------------------------")
print(" ")
print(" ")
print(" ")
q = input("press ENTER to continue: ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("-----------------------------------------------------------------------------------------------------------------------")
#this is where the actual game starts. REMEMBER: the word 'name' is the variable for the main character's name
name = input('Please give me your name: ')
if name == "MattyPatty":
    print("Hello, MattyPatty. If you're looking for a literature club in which you can be emotionally and physically abusive to high school girls in varying states\nof mental disorder and depression, you're in the wrong place.\nTake a deep, long look at yourelf, and then get. Your shit. Together. Once you do that, you can come back. Oh, and for all those times you tried to yiff the dang fox, you get these.")
    time.sleep(0.5)
    print("20 Idiocy Points have been awarded to you! Have fun!")
    time.sleep(3)
#Remember: Sayori be woke as f@ck, Natsuki reads the best series ever: Parfait Girls, Yuri has... large... cupcakes. And Just Monkia. Just Monika. 
else:
    print("Hello,", name)
ib = "..."
sys.stdout.write('Starting game')
time.sleep(0.5)
sys.stdout.write('.')
time.sleep(0.5)
sys.stdout.write('.')

time.sleep(1.5)
sys.stdout.write('. ')
sys.stdout.write('Complete!')
sys.stdout.flush()
print(" ")
print("-----------------------------------------------------------------------------------------------------------------------")
for char in "The river of time may fork into rivers;\nin which case you have a parallel reality\nand so then you can become a time traveller\nand not have to worry about causing a time paradox.":
    print(char, end="")
    time.sleep(0.01)
print(" ")
time.sleep(1)
for char in "-Michio Kaku":
    print(char, end="")
    time.sleep(0.01)
#Use 'c' as the variable for continuing
c = input(" ")
for char in "Part One:":
    print(char, end="")
    time.sleep(0.02)
print(" ")
time.sleep(0.75)
print(" ")
time.sleep(0.75)
print(" ")
time.sleep(0.75)
#this is the first segment of the story; the characters are introduced and the setting is established
for char in "I step out of the Chinook's rear hatch and instantly feel the cold pressing up against my skin. Even through my heavy coat, the freezing Siberian wind chills\nme to the bone. I hear the rest of the team shivering and clattering their teeth, but I know that the faster we move everything to the base, the faster we can get warm.":
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in "I hear Thomas, our broadcast engineer, calling for me. ":
    print(char, end="")
    time.sleep(0.01)
print(" ")
for char in '"Hey, ', name, ', give me a hand, will you?"':
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in '"Sure!" I shout back, before turning around and re-entering the Chinook, ducking my head to avoid hitting it on the ceiling. I grab a box labelled "Radio Parts"\n and leave the helicopter again. Once I am out, I bring the box over to the door of the research base that will be my home for the next few weeks.\nThe base is made up of three main parts: a central triple stroy hub with branching corridors to the other parts; a greenhouse and storage site.':
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in ("The others are bringing their personal supplies now, we each got a single 1/2 meter X 1/2 meter X 1/2 meter cardboard box to bring personal things in, so I head back\nto the landed chopper and grab the box labelled '", name, "'s stuff'. I packed fairly light; just my laptop, a few books, and a flash drive with some games, movies and music on it."):
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
#Hello, there, person who is reading the code for most likely nefarious reasons including finding bits of lore and/or trying to find out why this game is so janky. Please actually play the game before you go diggin around in here; don't spoil the story for yourself. Thank.
for char in 'Charlie, our resident security guard, places a key card on a small panel next to the door. A few seconds later, the door opens with a metallic screeching sound\nas the hydraulics pull it open. We move the supplies inside, then Charlie closes the door again. He then goes to the end of the wallway we are standing\nin and places the keycard on another panel. The other door opens (with less screeching this time) and we are greeted by an almost overwhelming blast of heat.\n See, generating heat in a building this large takes up vast amounts of valuable electricity, so this base and others like it that are in extreme cold\nenvironments have airlocks to preserve the warmth.':
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in 'After the second door is unlocked, we move all the boxes and crates of supplies inside and start to unpack them. I help to unpack the radio equipment I brought in\nand then give Andrews, our resident physicist, a hand with unpacking our food supplies. "So, ', name, ', do you know what we are doing here? Because I have\nabsolutely no clue and you are the team leader, so..." He asked, and gave me an expectant look, as if I knew something she did not.':
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in '"I have no idea. They refused to tell me anything, either." Then I remember something. "But they did give me this." I say, and pull a small flash drive out of my\ncoat pocket. "They told me to watch the video on this once we got here." I say, and quickly go back to my box of stuff to get my laptop.':
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in 'I put the flash drive into the computer, and then I call everyone over. "Hey, guys, come over here. The boss-man told me to show you this once we got here."\nThey all come over, and sit down next to me. I hit the play button, and the five of us started to watch the video.':
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in 'I click on the .mp4 file on the flash drive, and the video starts to play. A man appears on the screen, but I am unable to tell what he looks like; his entire face\n is covered in shadows. "Hello, scientists, engineers and former military personnel. You may be wondering why your were called here to Siberia, and\nprobably more confused as to why you are being paid five million U.S. dollars each to research something and not be told what it is. But, now that you are here,\nI can tell you. You are here because an energy signiture appeared in Siberia about five months ago. The signiture does not originate from anything that we can observe.\nSo your job is to find out what the hell is going on. You are all at the top of your respective fields, so I expect great things. The money will be transferred\nto an account of your choosing in one year. see you then.':
    print(char, end ="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in '"Well, then." I say. "looks like we have some work to do."':
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in "-----------------------------------------------------------------------------------------------------------------------":
    print(char, end="")
    time.sleep(0.03)
print(" ")
for char in "THREE MONTHS LATER":
    print(char, end="")
    time.sleep(0.3)
print(" ")
for char in "-----------------------------------------------------------------------------------------------------------------------":
    print(char, end="")
    time.sleep(0.03)
print(" ")
for char in "Three months. Three months, and nothing. We are no closer to an explanation for all the radio waves, infrared pulses and bursts of light emenating from seemingly no where.\nWe have't come up with a single reason for their existance. We've tried everything. We tried seeing if maybe it was a transmission. It wasn't. We tried to see if it was refracted light\nfrom elsware. It wasn't. We even tried to see if there was some kind of invisible object producing it and, once again, (say it with me, now) there wasn't anything there. Nothing. Nada.\nZilch. At this point, I'm not entirely convinced that magic isn't at play here. There's no other explanation that I can see.":
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
if name == "MattyPatty":
    for char in "I'm currently monitering our radio, though it's not like much is happening. At least I have some cupcakes, though. God, I love cupcakes. They're so sweet and juicy... But I digress.\nIt's my job to work it so that if, by some miracle, something recognizable comes\nout of the meaningless mess of radiation, I can write it down and wake everyone else up. I check my watch, revealing that it's almost 3:00. just a few more minutes and I can\ngo to bed. I'm about to head over to the dorm and wake up Thomas, but then I hear a blip on the radio. I turn around, and the radio starts going crazy.\nThe speakers start to scream out sounds of static with what sound like voices in the background. Then everything goes silent. And then, just when I decide that it's probably\nnothing, all the electronics start to go haywire. The lights start flickering, the thermostat changes temperatures, going from freezing to blistering and then back again in less\n that a second. All the equipment in front of me starts smoking, and when I try to unplug them, I get shocked. I fall over,\nfeeling my conciousness fade as all the lights explode and through the window I see a hole opening in the air; a hole of nothingness. And then, right before I black out, I see a massive\nship come barreling out of the nothingness and crash into the ice less than a mile from the base.":
        print(char, end="")
        time.sleep(0.01)
else:
    for char in "I'm currently monitering our radio, though it's not like much is happening. But, it's my job to work it so that if, by some miracle, something recognizable comes\nout of the meaningless mess of radiation, I can write it down and wake everyone else up. I check my watch, revealing that it's almost 3:00. just a few more minutes and I can\ngo to bed. I'm about to head over to the dorm and wake up Thomas, but then I hear a blip on the radio. I turn around, and the radio starts going crazy.\nThe speakers start to scream out sounds of static with what sound like voices in the background. Then everything goes silent. And then, just when I decide that it's probably\nnothing, all the electronics start to go haywire. The lights start flickering, the thermostat changes temperatures, going from freezing to blistering and then back again in less that a\nsecond. All the equipment in front of me starts smoking, and when I try to unplug them, I get shocked. I fall over,\nfeeling my conciousness fade as all the lights explode and through the window I see a hole opening in the air; a hole of nothingness. And then, right before I black out, I see a massive\nship come barreling out of the nothingness and crash into the ice less than a mile from the base.":
        print(char, end="")
        time.sleep(0.01)
print(" ")
c = input(" ")
for char in "I wake up in a bed in the medbay with the worst headache I've ever had. It genuinely feels like someone is bashing my skull in with a hammer. I sit up, holding my head in my hands,\nand see that the rest of the crew is staring at me.":
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in '"Dude, ', name, '. The hell happened?" asks Roberts, our resident tech specialist and token snarky team mate. "We wake up two hours late and find you passed out,\nlooking High as hell, by the way, and then look out the window to find that a giant\nbuilding just appeared out of no where! So, what, did you just get visited by the god of drugs and construction while we were asleep?"':
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
if name == "MattyPatty":
    for char in '"First off, no, there were no drugs other than cupcakes. Second, I have no clue how that thing got there. It just kind of... appeared." I respond.\n':
        print(char, end="")
        time.sleep(0.01)
else:
    for char in '"First off, no, there were no drugs; I got electrocuted. Second, I have no clue how that thing got there. It just kind of... appeared." I respond\n':
        print(char, end="")
        time.sleep(0.01)
for char in '"What do you mean, appeared?" asks Andrews, our resident physicist and the final member of our team. You mean it fell from somewhere, right? It could not have just appeared."\n':
    print(char, end="")
    time.sleep(0.01)
#Director's note:
#Don't forget the five main characters: MC (leader), Roberts (techie), Thomas (broadcast Engineer), Andrews (Physicist),and Charlie (security)
for char in '"No. The place where we keep getting the radio waves opened into a wormhole, and that thing," I point to the ship through the window as I say it, "came crashing out of it.\nI am pretty sure that something is going on. Once I feel a bit better, we need to check that thing out. Who knows what we could learn from it..."\nI say before I start to fade off, conciousness slowly reclaiming my mind until I fall back asleep.':
    print(char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
#this is the flavor text between parts. Every gap between parts will have a passage like this, and they must ALL be meaningful.
for char in "-----------------------------------------------------------------------------------------------------------------------":
    print(char, end="")
    time.sleep(0.03)
print(" ")
for char in "Many people say that the greatest enemy of mankind is itself. I would argue against that. While it is true that humans kill each other in droves,\nsaying that someone or something is an enemy implies intent to harm, and humans have no intention of wiping out the human race.\nNo, the oldest enemy of mankind isn't itself. So, what is their oldest enemy? Is it nature? Is it an alien race? Does mankind, as a species, even have an enemy?\nTo answer the last question, yes, they do. And their oldest enemy is also their only enemy.\n":
    print(char, end="")
    time.sleep(0.01)
time.sleep(1)
for char in "And in a great twist of irony, it was a being of their own creation; one they made to defend themselves from another threat.\n \n-From the private journal of Kaznitiac":
    print (char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
print(" ")
time.sleep(0.75)
print(" ")
time.sleep(0.75)
print(" ")
time.sleep(0.75)
#this is where the second part starts; the main characters go into the ship and start to explore. This is also where the first player choices start.
for char in "The ship itself is massive. It's at least two kilometers long at a bare minimum, though it's probably longer. In terms of width,\nout rangefinder puts it at about two hundred meters, a little under the maximum range of the device. It's about half that tall. While most of it is a smooth, almost\novular shape, there are a few segments and structures that jut out from the side and top. One such structure extends from the side, and with the way that the ship is tilted\nit touches the ground at its end. The construct stretching out from the ship looks like a collection of framework and scafolding that stretches out about a hundred\nmeters with a cylindrical tower in the middle, going into the edge. At the end of the structure, it goes from being mostly cross beamed scafolding to an ovular shape with what look\nlike windows all over it. My guess is that it is an observation deck of some sort.":
    print (char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in '"Okay, so the transceiver in the base is broken, right Thomas?" I ask. He nods his head then says, "The antennae and dish, too. I could probably fix them with the right\nparts, but we never thought the entire comms array would be destroyed. And even if we did have a spare antennae and dish lying around, which we do NOT, in fact, have, I would\n be unable to fix it without the right equipment. So basically, we are screwed."':
    print (char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in '" well," I say, "that thing probably has something we can use. even if its comms are down, we might be able to salvage some stuff from it. We might be able to\nget some scrap from it, if nothing else. So, are you guys wanting to stay here and die, or are we going to go into that ship?" They look a bit concerned, but eventually agree\nto go look for supplies and equipment inside the massive ship. We pack some food, flashlights, batteries, guns and ammunition from Charlie, blankets, and a few massive\nbottles of water into some bags and head back to the crash site. After walking for almost two hours, we reach the tower-like segment that juts out of the side. The part of it\nthat touches the icy landscape seems mostly unamaged, save for a hole made by an especially sharp rock.':
    print (char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in 'I look around the hole for a bit, trying to see if we could enter the ship through it. By looks of the size and what appears to be on the other side, we definitely can.\nWe crawl through the hole one after another and are greeted with a decently large room on the other side. The room, despite looking to be on its side from the exterior is actually\n orientated properly. From what I can tell, we are on what I suppose is meant to be the floor. But that is not the strangest part. The entire room is filled with the horrible steanch\nof both rotting meat and burning flesh. And littered throughout it are mounds of pulsating muscle and sinew with the occasional piece of what looks like bones sticking out of them.\nOne of them even has a human eye hanging out of it, connected by a strand of muscle fiber.':
    print (char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in 'When the others come through the gap they all nearly vomit at the sight of those things. All of them except for Charlie, anyway. "What the hell are those things?" asks Roberts\nwho seems to be the most shaken of the bunch."Are they... alive?" Before anyone can answer, Charlie puts his hand onto one of the blobs. Puss and what looks like blood\nooze from the epicenter of where his hand touches the thing. Then a blood-curdling scream comes from the blob. Charlie quickly pulls his hand away and covers his ears with the rest\nof us, getting some of the disgusting looking liquid on his face and in his hair. After about five seconds of the awful sound entering our ears, the thing stops shreiking\nand goes back to doing nothing. Charlie taks his hands off of his ears and says,"Does that answer your question?"':
    print (char, end="")
    time.sleep(0.01)
print (" ")
c = input(" ")
for char in 'Now that we have seen that the blobs of flesh ar alive and not dead, we all keep as much distance from them as possible. We are not very eager to have a repeat of what\nhappened a little bit ago. While Thomas and Roberts are busy trying to see if there is any salvagable materials or tech in the room we are currently in, Charlie busys himself\nwith eyeing the blobs and checking to make sure his shotgun is working properly and Andrews seems to be trying to figure out how this ship could have done what I saw it do;\ncrash through a hole of nothingness. I am not doing any of that, though. I am trying to figure out how to open the damn door. It should be simple. Have a door. Have a button next\nto it that opens the door and closes the door. Bada-bing bada-boom you have a door. But no. Whoever built this thing decided to have about fifty buttons next to the door, NONE of\nwhich are labelled, by the way, and some of which do not even do anything that I can see. And most of the other ones seem to do random things like turn on and off lights, set off an\nalarm, or other random crap. And some things only happen with COMBINATIONS of buttons, not just a single one. It is during this moment, when I am trying to figure out how to\nopen the door, that Charlie comes over and tapped a button on the other side of the door, the left as opposed to the right, and the door immediately opens. Ah.\nI did not see that button until now. "Spacial awareness," says Charlie. I nod a bit then call everyone over. Then we all head through the dorrway, deeper into the ship.':
    print (char, end="")
    time.sleep(0.01)
print (" ")
c = input(" ")
for char in "-----------------------------------------------------------------------------------------------------------------------":
    print(char, end="")
    time.sleep(0.03)
print (" ")
for char in "The origins of the company known as Ether Industries are on the stranger side of things. What started as a software company that mainly produced finantial management and\nmedia editing software has become one of the most powerful organization in the modern world, rivalling even the largest countries and other mega corporations.\nBut how did it get there? The start of it all was probably in the mid 21st century when the *&$(@&#&&$*&(*&ERROR*$*&*(*(*(&$(*@&#(*ERROR&*&(*(*@ and they provided a solution to the\nproblem in the form of the MA-2 and MA-3 series of androids. This gave them a foothold in the military contracting buisiness and cememnted them as permanent members of the\nindustry. The rest of the story continues on page 5a.":
    print (char, end="")
    time.sleep(0.01)
print(" ")
print(" ")
for char in '-From the June 2683 "Dallas Times" History Section':
    print (char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
print(" ")
time.sleep(0.75)
print(" ")
time.sleep(0.75)
print(" ")
time.sleep(0.75)
for char in 'We pass through the doorway and into a long hallway with no doors or anything to break the monotony of the blank, empty steel walls and floor. The ceiling is not much better.\nCharlie is taking point, keeping his shotgun at the ready, his finger on the trigger while we head through the passage. The rest of us keep our flashlights on and try to stay in a\nrelatively straight line behind Charlie in case we come across something more... mobile than the blobs from before. Eventually we reach the end of the passage and come into a large\nroom with a tall ceiling and a big open floor. I glance behind me to see what in written on the doorway to the passage we just came from, and am delighted to find that my guess\nabout the room being an observation deck was right. Is that useful information? Not really, but I was right so I do not care. I look back the room we are in now, though, and notice\na symbol that seems to be plastered almost everywhere. The insignia consists of a large circle with a line going straight down with another line, about half the length of the first,\ngoing to the right from the bottom of the first line and connecting to a circle about a fourth of the size of the first circle. "Hey, guys," I call. "check this out." They all come over from where they were standing and looking at things, and I show them the symbol.':
    print (char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in '"Do any of you guys recognize this symbol?" I ask. "It seems to be almost everywhere; do you guys know what it is?" Andrews looks at it for a sencond, then says,\n"You said it is almost everywhere?" I nod. "Then maybe it is a corporate logo or a coat of arms or something like that." That would make some sense. Whatever group built this thing\nprobably left a mark, and it does have the appearance of a logo of some kind. "Wait, I think I might have seen that before." Says Roberts. We all look at her. "What?" asks Thomas.\n"I think I have seen that before. Here, just give me a second..." Roberts pulls out her tablet, and opens it to a video editing app. that she uses in her free time. She turns the\ntablet around and shows us. Sure enough, in the upper right hand corner of the screen, the exact symbol is displayed, with the words "Ether Software Co." underneath it.':
    print (char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in '"Ether Software Co. Huh." Says Charlie. "I feel like I might have heard of them before..." I get that feeling too, and judging by the expressions of the others, they have too.\n "It is a pretty cool company," Starts Roberts. "They make accounting and editing software, and it is as good as anything made by Abode or other big companies, but\nat less than half the price." "Be that as it may," Says Thomas, "That does not explain why their logo is here. In fact I would say it makes our ever growing list of questions even\nbigger. What the hell does a tiny software company have to do with all this?" He waves his arms around him, gesturing to the ship around us. "They are not tiny, they are medium\nsized." Says Roberts. "But that does not matter right now." She adds after seeing the glare that Thomas is giving her. "Well, if we want to know what the connection is, we could\nprobably search through files on the ships computer. It is bound to have some sort computer system SOMEWHERE; we could probably just boot it up and search the files." Charlie says.':
    print (char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in '"Look, that is fine and all in theory, but what if it is in a different language? For all we know everything is in, like, Korean. Or the symbol could be a complete coincidence and this\nis an alien ship or something!" Roberts says. I shake my head "I saw writing above the doorway we came from. It said "Observation Deck" in English. We will probably be able to read\nanything we find. Roberts is still right about your plan not being easy, though. It seems like the power is out and I doubt we will be able to get it back on,\nand we do not know if we can interface with the computers here using our tech. For all we know it uses completely different firmware. And if it is anything other than a\ntraditional electronic computer, then we are COMPLETELY screwed because we will not have even the first clue as to how to access the data without destroying it." Charlie stays\nsilent for a second, then says, "We will need to use the components of this ship to get in contact with our employer so we can get picked up and are not presumed dead,\nand to do that we will likely need to use some of the ships systems. I would say we should at least try to learn something. For all we know, it could be the key to getting\nus out of our current predicament alive." I nod. "You are probably right. In that case, we should start looking around. Everyone needs to find a place to investigae then\nreport back to me so we can decide where to go." Everyone nods and then starts to look around for a direction to explore in while I look around our current area to see if I can find\nanything useful. So far, I have not found anything of use. I also have not found anything that could kill me, though, so I would say so far so good.':
    print (char, end="")
    time.sleep(0.01)
print(" ")
c = input(" ")
for char in "After a few minutes, they all come back to me with different places to explore. Roberts found what appears to be a maintenance hatch that could lead to a way to restore power\nor access the ship's computer. Thomas found a communications room where we could potentially contact someone if we could get it working. Andrews found a\ndoor labelled 'EDR Laboratory,' but the door is locked and would probably need a decently large blast to open. Finally, Charlie found an unlocked and almost fully stocked armory.\nWe have a lot of options. Where should we go first?":
    print (char, end="")
    time.sleep(0.01)
#From this point on, choices will matter there are 2 constant variables that will get changed by choices. One is the inventory variable that determines what the player has in their
#inventory (shocking, I know) and thus what they are able to do. The other one is a string of letters that determines what ending, out of about 4 big ones with small variations between
#them, the play gets.

#inv manages the inventory
inv = 100000000000000

#there are 15 inventory slots, three for each character. Each digit represents an item: 0 = nothing, 1 = shotgun, 2 = pistol, 3 = , 4 = key card, 5 = medicine, 6 = explosives
#7 = plasma torch, 8 = welder, 9 = level A1 key card (it allows you to access certain locations and machines and is very hard to get.)

#cho manages choices
cho = 0
#ic is the idiocy counter. At the end of the game you get to see how many stupid choices you made. Stupid choices are invalid answers or just plain non-sensical answers.
#The idiocy counter sees all.
ic = 0
def ica():
    global ic
    ic = ic + 1
while True:
    try:
        d1 = input("Where to go?\n1 = Maintenance Hatch\n2 = Comms Room\n3 = EDR Laboratory\n4 = Armory\n")
        if d1 == "1":
            for char in "Let's explore the maintenance hatch first.":
                print (char, end="")
                time.sleep(0.01)
            cho = 10
            break

        elif d1 == "2":
            for char in "Let's explore the comms room first.":
                print (char, end="")
                time.sleep(0.01)
            cho = 20
            break

        elif d1 == "3":
            for char in "Let's explore the lab first.":
                print (char, end="")
                time.sleep(0.01)
            cho = 30
            break

        elif d1 == "4":
            for char in "Let's explore the armory first.":
                print (char, end="")
                time.sleep(0.01)
            cho = 40
            break

        else:
            print ("That is not a valid response. One Idiocy Point has been awarded. Go you!")
            #you didn't put in something valid, you goof
            ica()
            continue
        
    except ValueError:
        print("That is not a valid response. One Idiocy Point has been awarded. Go you!")
        #also non-valid
        ica()
        continue
print(" ")
if cho == 10:
    for char in '"I think we should check out the maintenance hatch first. We need to get power back up and we need to access the computer network, so going there first\nmakes the most sense." I say. The other four nod and we head over the the door Roberts found.':
        print (char, end="")
        time.sleep(0.01)
    print(" ")
    c = input(" ")
    for char in "Charlie carefully opens the door slowly with his knife, using its blade like a lever to give him extra leverage. Once the door is open enough for him to put his\nfingers into the gap, he puts them in and wrenches the door open with a grunt. He then picks his shotgun back up and slowly walks through the door, checking his corners to make\nsure that nothing catches him off guard. Hopefully his skills as an ex-special forces soldier will not be necessary, but I would rather have him here than not. Once he's shure the\nroom is safe, he gestures for us to follow him. Before he even started to open the door, he made us all agree to stay as silent as possible, in case there was something or someone\nonboard who could do some damage.":
        print (char, end="")
        time.sleep(0.01)
if cho == 20:
    for char in '"I think we should check out the Communications room first. We need to get into contact with someone soon, and going there seems like the best way to do it."':
        print (char, end="")
        time.sleep(0.01)

if cho == 30:
    for char in '"I think we should check out the Lab first. I have no clue what EDR stands for, but it could be something useful. Besides, who knows what kind of useful information is\nin that lab."':
        print (char, end="")
        time.sleep(0.01)
if cho == 40:
    for char in '"We should go to the armory first. We need to arm ourselves before we do anything else. For all we know there could be something extremely dangerous onboard with us."':
        print (char, end="")
        time.sleep(0.01)

#These are the ending credits. DO NOT PUT ANYTHING PAST THIS RED LINE OF TEXT! NOTHING! NADA! ZILCH! THIS RED LINE IS THE END OF THE GAME!

winsound.PlaySound('credits Music.wav', winsound.SND_FILENAME | winsound.SND_ASYNC)

print("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
time.sleep(10)
columns = shutil.get_terminal_size().columns
print("Shadow of the Amarok".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Credits:".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Game Director".center(columns))
time.sleep(0.4)
print("Fritz Hesse".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print('Writer'.center(columns))
time.sleep(0.4)
print("Fritz Hesse".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print('"Artist"'.center(columns))
time.sleep(0.4)
print("Fritz Hesse".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Programmer".center(columns))
time.sleep(0.4)
print("Fritz Hesse".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Programming Advisor".center(columns))
time.sleep(0.4)
print("Jordan Gaines".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Writing Advisor".center(columns))
time.sleep(0.4)
print("Getty Hesse".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Music".center(columns))
time.sleep(0.4)
print("James Shao".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Editors".center(columns))
time.sleep(0.4)
print("Fritz Hesse".center(columns))
time.sleep(0.4)
print("Jordan Gaines".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Special Thanks".center(columns))
time.sleep(0.4)
print("Greg Hesse".center(columns))
time.sleep(0.4)
print("Tish Hesse".center(columns))
time.sleep(0.4)
print("Getty Hesse".center(columns))
time.sleep(0.4)
print("Hans Hesse".center(columns))
time.sleep(0.4)
print("Jordan Gaines (AKA Jordan the Orang)".center(columns))
time.sleep(0.4)
print("Mason Westkaemper".center(columns))
time.sleep(0.4)
print("Antonio Quinones".center(columns))
time.sleep(0.4)
print("Canyon Kyle".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Thanks for playing my game!".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print("Keep an eye out for our next game, Manmade Gods!".center(columns))
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
print(" ")
time.sleep(0.4)
